apiVersion: v1
kind: Secret
metadata:
  name: {{ include "justnews.fullname" . }}-postgres-secrets
  labels:
    {{- include "justnews.labels" . | nindent 4 }}
    app: postgres
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  PGDATA: "/var/lib/postgresql/data/pgdata"